package httpserver

func (s *Server) routes() {
	s.mux.Handle("GET /assets/", s.assets())
	s.mux.HandleFunc("GET /healthz", s.health)
	s.mux.HandleFunc("GET /", s.index)
	s.mux.HandleFunc("GET /setup", s.setupForm)
	s.mux.HandleFunc("POST /setup", s.setupPost)
	s.mux.HandleFunc("GET /login", s.loginForm)
	s.mux.HandleFunc("POST /login", s.loginPost)
	s.mux.HandleFunc("POST /logout", s.logoutPost)
	s.mux.HandleFunc("GET /admin", s.admin(s.adminHome))
	s.mux.HandleFunc("GET /admin/settings", s.admin(s.settingsForm))
	s.mux.HandleFunc("POST /admin/settings/media-server", s.adminPost(s.settingsPost))
	s.mux.HandleFunc("GET /admin/webhooks", s.admin(s.webhooksList))
	s.mux.HandleFunc("POST /admin/webhooks", s.adminPost(s.webhooksCreate))
	s.mux.HandleFunc("POST /admin/webhooks/{id}/delete", s.adminPost(s.webhooksDelete))
	s.mux.HandleFunc("POST /admin/webhooks/{id}/test", s.adminPost(s.webhooksTest))
	s.mux.HandleFunc("GET /admin/audit", s.admin(s.auditList))
	s.mux.HandleFunc("GET /admin/invites", s.admin(s.invitesList))
	s.mux.HandleFunc("GET /admin/invites/new", s.admin(s.invitesNew))
	s.mux.HandleFunc("POST /admin/invites", s.adminPost(s.invitesCreate))
	s.mux.HandleFunc("POST /admin/invites/{id}/disable", s.adminPost(s.invitesDisable))
	s.mux.HandleFunc("POST /admin/invites/{id}/enable", s.adminPost(s.invitesEnable))
	s.mux.HandleFunc("POST /admin/invites/{id}/delete", s.adminPost(s.invitesDelete))
	s.mux.HandleFunc("GET /admin/templates", s.admin(s.templatesList))
	s.mux.HandleFunc("POST /admin/templates", s.adminPost(s.templatesCreate))
	s.mux.HandleFunc("GET /admin/templates/{id}", s.admin(s.templatesShow))
	s.mux.HandleFunc("POST /admin/templates/{id}", s.adminPost(s.templatesUpdate))
	s.mux.HandleFunc("POST /admin/templates/{id}/default", s.adminPost(s.templatesDefault))
	s.mux.HandleFunc("POST /admin/templates/{id}/delete", s.adminPost(s.templatesDelete))
	s.mux.HandleFunc("POST /admin/templates/import-from-user", s.adminPost(s.templatesImport))
	s.mux.HandleFunc("GET /admin/registrations", s.admin(s.registrationsList))
	s.mux.HandleFunc("POST /admin/registrations/{id}/retry-template", s.adminPost(s.registrationsRetryTemplate))
	s.mux.HandleFunc("GET /i/{token}", s.publicInvite)
	s.mux.HandleFunc("POST /i/{token}/register", s.publicRegister)
	s.mux.HandleFunc("GET /success", s.success)
	s.mux.HandleFunc("GET /guide", s.guide)
}
